# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: "default"
variables:
- name: CloudInitContent

steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script:
        # write your powershell command here.
        $CloudContent= Get-Content -Path $(Build.SourcesDirectory)\Devoir1_\Devoir1_\Cloud-Init.txt -Raw
        write-Host $CloudContent
        $encodedContent = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($CloudContent))
        write-Host $encodedContent
        write-Host "##vso[task.setvariable variable=CloudInitContent;]$encodedContent"
  - script:
      echo $(CloudInitContent)
